#pragma once

#ifndef __ENUM_H__

enum Layer { LAYER_0, LAYER_1, LAYER_2, LAYER_3, LAYER_4,LAYER_5,LAYER_END };

enum ANIMATION_TYPE{ANIMATION_LOOP,ANIMATION_ONCE};

enum COLLIDE_TYPE{NORMAL,LEFT_TOP,LEFT_BOTTOM,RIGHT_TOP,RIGHT_BOTTOM};

#define __ENUM_H__
#endif